package portaltek.hexa.domain.enums;

public enum ErrorType {
    //ImportCatalog
    COMPANY_IS_EMPTY,
    FISCAL_PERIOD_IS_EMPTY,
    ACCOUNT_LIST_IS_EMPTY,
    ACCOUNT_IS_INVALID,
    ACCOUNT_ID_DUPLICATED,
    ACCOUNT_CODE_DUPLICATED,
    ACCOUNT_CODE_IS_EMPTY,
    ACCOUNT_NAME_IS_EMPTY,
    ACCOUNT_DESCRIPTION_IS_EMPTY,

    COMPANY_NOT_FOUND,
    FISCAL_PERIOD_NOT_FOUND,

}
